#cloud-config
autoinstall:
    version: 1
    identity:
        realname: "Melquisedec"
        hostname: ubuntu
        username: melquisedec
        password: "$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3"
    locale: pt_BR.utf8
    keyboard:
        layout: br
	      variant: intl
    timezone: "America/Sao_Paulo"
    packages:
      	- curl
      	- git
    late-commands:
	      - curtin in-target -- /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
