#cloud-config
autoinstall:
    version: 1
    source:
        id: ubuntu-desktop-minimal
    interactive-sections:
        - storage
    identity:
        realname: 'Melquisedec'
        hostname: ubuntu
        username: melquisedec
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: "pt_BR.utf8"
    keyboard:
        layout: "us"
        variant: "intl"
    timezone: "America/Sao_Paulo"   
    packages:
        - curl
        - git
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
